name: Release
on:
  push:
    branches:
      - 'main'
      - 'v[0-9]+.[0-9]+.x'
  schedule:
    - cron: '0 8 * * *' # run at 8am UTC
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Public Api Check
        run: npm run public-api:check
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
        run: npx semantic-release
